Repository carbon-design-system/carbon-charts, pull requests merged in 2020-02, with the labels that each got.

#422 feat(scatter): add the entire datapoint as a parameter to the callbacks to determine custom point colors
  packages/core/demo/demo-data/line.ts
  packages/core/src/components/essentials/tooltip-bar.ts
  packages/core/src/components/essentials/tooltip-scatter.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/model.ts
Labels: enhancement

#485 feat(core): sanitize data
  packages/core/demo/demo-data/pie-donut.ts
  packages/core/src/components/graphs/pie.ts
  packages/core/src/model-pie.ts
  packages/core/src/model.ts
  scripts/deploy.sh
  yarn-offline-mirror-cache/detect-libc-1.0.3.tgz
  yarn-offline-mirror-cache/needle-2.3.2.tgz
  yarn-offline-mirror-cache/node-pre-gyp-0.14.0.tgz
  yarn.lock
Labels: core, enhancement

#508 Make carbon-components a devDependency
  packages/core/package.json
Labels: build-process, enhancement

#496 fix(core): Tools.getProperty did return 'null' for falsy values
  packages/core/src/tools.spec.ts
  packages/core/src/tools.ts
Labels: bug 🐛

#517 add deploys by netlify badge to core demo
  packages/core/demo/index.html
  packages/core/demo/index.scss
Labels: demos, documentation 📖

#491 optional domain setting
  packages/core/demo/demo-data/bar.ts
  packages/core/demo/demo-data/index.ts
  packages/core/src/interfaces/axis-scales.ts
  packages/core/src/services/scales-cartesian.ts
Labels: accurat, enhancement
