Repository carbon-design-system/carbon-charts, pull requests merged in 2020-03, with the labels that each got.

#524 Fix function that calculates size of SVG DOM elements
  packages/core/src/services/essentials/dom-utils.ts
Labels: bug 🐛

#525 add mouse events for axis labels
  packages/core/src/components/axes/axis.ts
  packages/core/src/interfaces/events.ts
Labels: enhancement

#530 Timeseries axis: Fix rotating tick when is not necessary
  packages/core/demo/demo-data/index.ts
  packages/core/demo/demo-data/line.ts
  packages/core/src/components/axes/axis.ts
Labels: accessibility, enhancement

#464 gaps within data
  packages/core/demo/demo-data/bar.ts
  packages/core/demo/demo-data/line.ts
  packages/core/src/components/graphs/line.ts
  packages/core/src/components/graphs/scatter.ts
Labels: severity: HIGH, specs-needed 🙏

#542 apply default charting dimensions through CSS rather than inline styles
  packages/core/src/configuration.ts
  packages/core/src/styles/_chart-holder.scss
Labels: enhancement

#543 Tslint: Add rules about trailing comma and space before function parenthesis
  packages/core/tslint.json
Labels: build-process

#548 fix(core): update import path carbon-components
  packages/core/src/components/component.ts
  packages/core/src/components/essentials/legend.spec.ts
  packages/core/src/components/essentials/title.spec.ts
  packages/core/src/components/essentials/tooltip-bar.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/services/essentials/dom-utils.ts
  packages/core/src/tests/tools.ts
Labels: bug 🐛
