Repository carbon-design-system/carbon-charts, pull requests merged in 2020-09, with the labels that each got.

#787 fix the defect of label tooltip not showing when using custom tooltip
  packages/core/src/components/essentials/tooltip.ts
Labels: bug 🐛

#793 feat: keep initialZoomDomain in model to detect change
  packages/core/src/components/axes/zoom-bar.ts
Labels: enhancement

#761 feat: enable chart grid enable option
  packages/core/src/components/axes/grid.ts
  packages/core/src/components/axes/ruler.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/styles/components/_grid.scss
Labels: enhancement

#770 feat: create options for tick rotation
  packages/core/src/components/axes/axis.ts
  packages/core/src/interfaces/axis-scales.ts
  packages/core/src/interfaces/enums.ts
Labels: enhancement

#769 feat: enable or disable scatter dot on charts except scatter chart
  packages/core/src/components/graphs/scatter-stacked.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
Labels: enhancement

#780 fix(meter) render max width bar for values over 100
  packages/core/src/components/essentials/title-meter.ts
  packages/core/src/components/graphs/gauge.ts
  packages/core/src/components/graphs/meter.ts
  packages/core/src/model-meter.ts
Labels: bug 🐛

#765 feat: enable or disable ruler
  packages/core/src/components/axes/ruler.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/components.ts
Labels: enhancement

#807 feat(angular): enable Angular 10
  packages/angular/package.json
Labels: angular, enhancement

#809 fix(core): fix valueFormatter not being called on non-axis tooltips
  packages/core/src/components/essentials/tooltip-axis.ts
  packages/core/src/components/essentials/tooltip.ts
Labels: bug 🐛

#815 fix(core): add aria-hidden attribute to tooltips
  packages/core/src/components/essentials/tooltip.ts
Labels: accessibility, enhancement

#811 fix: do not dispatch zoom domain change event for all zoom bar behaviors
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/services/zoom.ts
Labels: enhancement

#805 Fix custom ticks
  packages/core/src/components/axes/axis.ts
Labels: bug 🐛

#781 Linear gradient option for area chart
  packages/core/demo/data/area.ts
  packages/core/demo/data/index.ts
  packages/core/src/chart.ts
  packages/core/src/components/graphs/area.ts
  packages/core/src/components/graphs/scatter-stacked.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/services/essentials/gradient-utils.ts
  packages/core/src/services/index.ts
Labels: design-approved ✅

#819 improvement(core): keyboard-navigatable legend items & accessibility fixes
  packages/core/CHANGELOG.md
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/ruler.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/title-meter.ts
  packages/core/src/components/essentials/tooltip-axis.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/components/graphs/area.ts
  packages/core/src/components/graphs/gauge.ts
  packages/core/src/components/graphs/meter.ts
  packages/core/src/components/graphs/pie.ts
  packages/core/src/components/graphs/scatter-stacked.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/components/graphs/skeleton.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/a11y.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/model-meter.ts
  packages/core/src/services/essentials/gradient-utils.ts
  packages/vue/CHANGELOG.md
Labels: accessibility, enhancement

#824 Fix string number values
  packages/core/src/model.ts
Labels: bug 🐛

#823 fix: allow string dates in zoom bar configurations
  packages/core/demo/data/index.ts
  packages/core/demo/data/zoom-bar.ts
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/services/zoom.ts
Labels: bug 🐛
