Repository carbon-design-system/carbon-charts, pull requests merged in 2020-12, with the labels that each got.

#890 Combo tutorial
  packages/core/stories/tutorials/combo-charts.ts
  packages/core/stories/tutorials/index.ts
Labels: documentation 📖

#901 Fix custom fill
  packages/core/src/components/graphs/radar.ts
  packages/core/src/components/graphs/scatter.ts
Labels: bug 🐛

#900 fix(core): fix font size issues with title tooltips
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/styles/components/_tooltip.scss
Labels: accessibility, bug 🐛, ui/ux ✨

#897 fix(interfaces): Updating Combo Chart Option type
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
Labels: bug 🐛
