Repository carbon-design-system/carbon-charts, pull requests merged in 2020-05, with the labels that each got.

#598 Ruler fix
  packages/core/src/components/axes/ruler.ts
Labels: bug 🐛

#569 Add Svelte wrappers
  packages/core/demo/data/create-codesandbox.ts
  packages/core/demo/data/index.ts
  packages/svelte/.babelrc
  packages/svelte/.storybook/addons.js
  packages/svelte/.storybook/config.js
  packages/svelte/.storybook/preview-head.html
  packages/svelte/README.md
  packages/svelte/build.sh
  packages/svelte/package.json
  packages/svelte/rollup.config.js
  packages/svelte/src/BarChartGrouped.svelte
  packages/svelte/src/BarChartSimple.svelte
  packages/svelte/src/BarChartStacked.svelte
  packages/svelte/src/BaseChart.svelte
  packages/svelte/src/BubbleChart.svelte
  packages/svelte/src/DonutChart.svelte
  packages/svelte/src/LineChart.svelte
  packages/svelte/src/PieChart.svelte
  packages/svelte/src/ScatterChart.svelte
  packages/svelte/src/index.js
  packages/svelte/stories/ChartWrapper.svelte
  packages/svelte/stories/all.stories.js
  yarn-offline-mirror-cache/@storybook-addons-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-api-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-channel-postmessage-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-channels-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-client-api-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-client-logger-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-components-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-core-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-core-events-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-node-logger-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-router-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-svelte-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-theming-5.3.18.tgz
  yarn-offline-mirror-cache/@storybook-ui-5.3.18.tgz
  yarn-offline-mirror-cache/@types-react-syntax-highlighter-11.0.4.tgz
  yarn-offline-mirror-cache/require-relative-0.8.7.tgz
  yarn-offline-mirror-cache/rollup-plugin-svelte-5.2.1.tgz
  yarn-offline-mirror-cache/svelte-3.20.1.tgz
  yarn-offline-mirror-cache/svelte-dev-helper-1.1.9.tgz
  yarn-offline-mirror-cache/svelte-loader-2.13.6.tgz
  yarn.lock
Labels: enhancement

#600 fix vue type check for charting data
  packages/vue/src/ccv-base-chart.vue
Labels: bug 🐛

#581 Radar
  packages/core/demo/data/index.ts
  packages/core/demo/data/radar.ts
  packages/core/src/charts/index.ts
  packages/core/src/charts/radar.ts
  packages/core/src/components/essentials/tooltip-radar.ts
  packages/core/src/components/graphs/radar.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/interfaces/events.ts
  packages/core/src/services/angle-utils.ts
  packages/core/src/styles/graphs/_radar.scss
  packages/core/src/styles/graphs/index.scss
  packages/core/src/tools.ts
Labels: enhancement

#599 Getting started tutorials
  packages/core/stories/tutorials.stories.ts
  packages/core/stories/tutorials/getting-started/angular.ts
  packages/core/stories/tutorials/getting-started/react.ts
  packages/core/stories/tutorials/getting-started/vanilla.ts
  packages/core/stories/tutorials/getting-started/vue.ts
  packages/core/stories/tutorials/index.ts
  packages/core/stories/tutorials/tabular-data-format.ts
Labels: documentation 📖

#607 Fix hover color logics for Bars hover
  packages/core/src/components/graphs/bar-grouped.ts
  packages/core/src/components/graphs/bar-simple.ts
  packages/core/src/components/graphs/bar-stacked.ts
Labels: bug 🐛

#555 Skeletons & empty states
  packages/core/demo/data/bar.ts
  packages/core/demo/data/bubble.ts
  packages/core/demo/data/donut.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/demo/data/pie.ts
  packages/core/demo/data/scatter.ts
  packages/core/demo/data/step.ts
  packages/core/src/charts/bar-grouped.ts
  packages/core/src/charts/bar-simple.ts
  packages/core/src/charts/bar-stacked.ts
  packages/core/src/charts/bubble.ts
  packages/core/src/charts/donut.ts
  packages/core/src/charts/line.ts
  packages/core/src/charts/pie.ts
  packages/core/src/charts/scatter.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/grid.ts
  packages/core/src/components/axes/zero-line.ts
  packages/core/src/components/graphs/bar.ts
  packages/core/src/components/graphs/donut.ts
  packages/core/src/components/graphs/skeleton.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/model.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/styles/components/_skeleton.scss
  packages/core/src/styles/components/index.scss
  packages/core/src/tools.ts
  packages/core/stories/all.stories.ts
Labels: accessibility, enhancement, ui/ux ✨

#564 Threshold
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/src/charts/line.ts
  packages/core/src/components/axes/two-dimensional-axes.ts
  packages/core/src/components/essentials/threshold.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/components/index.ts
  packages/core/src/interfaces/axis-scales.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/interfaces/events.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/styles/components/_threshold.scss
  packages/core/src/styles/components/index.scss
  packages/core/src/styles/graphs/_scatter.scss
Labels: accessibility, enhancement

#606 Tutorials - Event listeners
  packages/core/stories/tutorials.stories.ts
  packages/core/stories/tutorials/event-listeners.ts
  packages/core/stories/tutorials/getting-started/angular.ts
  packages/core/stories/tutorials/getting-started/react.ts
  packages/core/stories/tutorials/getting-started/vanilla.ts
  packages/core/stories/tutorials/getting-started/vue.ts
  packages/core/stories/tutorials/index.ts
  packages/core/stories/tutorials/tabular-data-format.ts
Labels: documentation 📖

#609 Time series labels bug
  packages/core/demo/data/index.ts
  packages/core/demo/data/time-series-axis.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/services/time-series.spec.ts
  packages/core/src/services/time-series.ts
Labels: bug 🐛

#616 replace carbon-components import to use es modules
  packages/core/src/components/essentials/threshold.ts
Labels: core

#615 hide invisible axes components
  packages/core/src/styles/components/_axis.scss
Labels: bug 🐛

#613 Fix axis rotation angle
  packages/core/src/components/axes/axis.ts
Labels: accessibility, bug 🐛

#629 add style import for angular
  packages/core/demo/data/create-codesandbox.ts
  packages/core/stories/tutorials.stories.ts
  packages/core/stories/tutorials/getting-started/angular.ts
  packages/core/stories/tutorials/getting-started/react.ts
  packages/core/stories/tutorials/getting-started/vue.ts
Labels: documentation 📖

#624 add IBM Plex font to codesandbox examples
  packages/core/demo/create-codesandbox.ts
  packages/core/demo/data/index.ts
Labels: demos, documentation 📖

#633 chore(core): fix repo urls in package configurations
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  package.json
  packages/angular/CHANGELOG.md
  packages/angular/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/svelte/CHANGELOG.md
  packages/svelte/package.json
  packages/vue/CHANGELOG.md
  packages/vue/package.json
  scripts/prepush.sh
Labels: documentation 📖

#638 fix(svelte): support Svelte CodeSandbox demos
  packages/core/src/components/essentials/threshold.ts
  packages/svelte/build.sh
  packages/svelte/rollup.config.js
  packages/svelte/src/BaseChart.svelte
Labels: bug 🐛, svelte

#412 feat(core): add area chart
  packages/angular/src/area-chart.component.ts
  packages/angular/src/charts.module.ts
  packages/core/demo/data/area.ts
  packages/core/demo/data/index.ts
  packages/core/src/charts/area.ts
  packages/core/src/charts/index.ts
  packages/core/src/components/graphs/area.ts
  packages/core/src/components/graphs/line.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/styles/graphs/_area.scss
  packages/core/src/styles/graphs/index.scss
  packages/core/src/styles/vendor/@carbon/layout/LICENSE
  packages/core/src/styles/vendor/@carbon/layout/README.md
  packages/core/src/styles/vendor/@carbon/layout/docs/sass.md
  packages/core/src/styles/vendor/@carbon/layout/es/index.js
  packages/core/src/styles/vendor/@carbon/layout/lib/index.js
  packages/core/src/styles/vendor/@carbon/layout/package.json
  packages/core/src/styles/vendor/@carbon/layout/scss/_breakpoint.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/_convert.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/_key-height.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/_mini-unit.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/_spacing.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/_utilities.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/generated/_container.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/generated/_fluid-spacing.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/generated/_icon-size.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/generated/_layout.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/generated/_spacing.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/index.scss
  packages/core/src/styles/vendor/@carbon/layout/scss/layout.scss
  packages/core/src/styles/vendor/@carbon/layout/src/index.js
  packages/core/src/styles/vendor/@carbon/layout/src/tokens.js
  packages/core/src/styles/vendor/@carbon/layout/umd/index.js
  packages/react/src/area-chart.js
  packages/react/src/index.js
  packages/svelte/src/AreaChart.svelte
  packages/svelte/src/index.js
  packages/vue/src/ccv-area-chart.vue
  packages/vue/src/index.js
Labels: core, demos, enhancement
