Repository carbon-design-system/carbon-charts, pull requests merged in 2020-07, with the labels that each got.

#686 feat(svelte): add Gauge chart wrapper
  packages/svelte/src/GaugeChart.svelte
  packages/svelte/src/index.js
Labels: svelte

#690 chore(angular): add angular 9 dependency versions to peerDependencies
  packages/angular/package.json
Labels: angular

#639 Show pre-selected data groups
  packages/core/demo/data/bar.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/layout/layout.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/model.ts
  packages/core/src/selectedGroups.spec.ts
  packages/core/src/tests/test-environment.ts
Labels: enhancement

#692 Fix bar chart tooltip data
  packages/core/src/components/essentials/tooltip-bar.ts
Labels: bug 🐛

#694 Remove primary and secondary options from demo
  packages/core/demo/data/bar.ts
  packages/core/src/services/scales-cartesian.ts
Labels: demos

#704 feat(core): add title element to main SVG
  packages/core/CHANGELOG.md
  packages/core/demo/data/bar.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/layout/layout.ts
  packages/core/src/model.ts
  packages/core/src/services/essentials/dom-utils.ts
  packages/vue/CHANGELOG.md
Labels: accessibility

#695 Tooltip redesign
  packages/core/CHANGELOG.md
  packages/core/demo/data/bubble.ts
  packages/core/src/axis-chart.ts
  packages/core/src/chart.ts
  packages/core/src/charts/area-stacked.ts
  packages/core/src/charts/area.ts
  packages/core/src/charts/bar-grouped.ts
  packages/core/src/charts/bar-simple.ts
  packages/core/src/charts/bar-stacked.ts
  packages/core/src/charts/bubble.ts
  packages/core/src/charts/donut.ts
  packages/core/src/charts/gauge.ts
  packages/core/src/charts/line.ts
  packages/core/src/charts/pie.ts
  packages/core/src/charts/radar.ts
  packages/core/src/charts/scatter.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/grid.ts
  packages/core/src/components/axes/ruler-stacked-bar.ts
  packages/core/src/components/axes/ruler.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/title.ts
  packages/core/src/components/essentials/tooltip-axis.ts
  packages/core/src/components/essentials/tooltip-bar.ts
  packages/core/src/components/essentials/tooltip-pie.ts
  packages/core/src/components/essentials/tooltip-radar.ts
  packages/core/src/components/essentials/tooltip-scatter.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/components/graphs/area-stacked.ts
  packages/core/src/components/graphs/bar-grouped.ts
  packages/core/src/components/graphs/bar-simple.ts
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/components/graphs/pie.ts
  packages/core/src/components/graphs/radar.ts
  packages/core/src/components/graphs/scatter-stacked.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/interfaces/events.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/styles/components/_ruler.scss
  packages/core/src/styles/components/_tooltip.scss
  packages/vue/CHANGELOG.md
Labels: accessibility

#706 fix(core, react, angular, vue, svelte): render both vertical and horizontal thresholds
  packages/core/src/components/essentials/threshold.ts
Labels: bug 🐛

#705 chore(angular): allow zone.js versions of ^0.10.0
  packages/angular/package.json
Labels: angular

#701 Fix hidden axes for charts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/graphs/skeleton.ts
Labels: bug 🐛

#707 Improve accessibility with aria-labels
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/ruler.ts
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/components/graphs/pie.ts
Labels: accessibility

#713 Custom tick values
  packages/core/demo/data/bar.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/interfaces/axis-scales.ts
Labels: enhancement

#710 Add align center flag for non-axis charts and legend
  packages/core/demo/data/bar.ts
  packages/core/demo/data/donut.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/demo/data/pie.ts
  packages/core/demo/data/radar.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/graphs/pie.ts
  packages/core/src/components/graphs/radar.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/services/essentials/dom-utils.ts
Labels: enhancement

#716 Fix pie chart alignment
  packages/core/src/components/graphs/pie.ts
Labels: bug 🐛

#715 Remove space on edge on custom domain
  packages/core/src/components/axes/axis.ts
Labels: bug 🐛

#709 fix(core, angular, vue, react, svelte): debounce ruler renders when more than 100 datapoints
  packages/core/CHANGELOG.md
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/ruler-stacked-bar.ts
  packages/core/src/components/axes/ruler.ts
  packages/core/src/components/essentials/threshold.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/components/graphs/pie.ts
  packages/core/src/tools.ts
  packages/vue/CHANGELOG.md
Labels: bug 🐛

#711 adjust the bar width to prevent bars from overlapping
  packages/core/demo/data/bar.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/graphs/bar.ts
Labels: accessibility, bug 🐛

#726 Fix stacked area chart in vue
  packages/vue/src/ccv-stacked-area-chart.vue
Labels: bug 🐛, vue
