Repository carbon-design-system/carbon-charts, pull requests merged in 2020-11, with the labels that each got.

#852 Color palette dropdown for storybook
  packages/core/CHANGELOG.md
  packages/core/demo/data/bar.ts
  packages/core/demo/styles.scss
  packages/core/src/components/graphs/scatter-stacked.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/model.ts
  packages/core/src/styles/colors.scss
  packages/core/src/styles/components/_toolbar.scss
  packages/core/stories/all.stories.ts
  packages/core/stories/utils.ts
  packages/vue/CHANGELOG.md
Labels: demos, enhancement

#856 fix(core): sanitize date values in the data
  packages/core/CHANGELOG.md
  packages/core/src/charts/line.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/components/graphs/line.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/components/graphs/skeleton-lines.ts
  packages/core/src/model.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/services/zoom.ts
  packages/vue/CHANGELOG.md
Labels: enhancement

#855 fix(zoombar): cache zoombar data and zoombar default domain
  packages/angular/stories/all.stories.ts
  packages/core/demo/data/high-scale.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/zoom-bar.ts
  packages/core/src/axis-chart.ts
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/model-cartesian-charts.ts
  packages/core/src/services/zoom.ts
  packages/core/stories/all.stories.ts
  packages/core/stories/utils.ts
  packages/react/stories/all.stories.js
  packages/svelte/stories/all.stories.js
  packages/vue/stories/all.stories.js
Labels: enhancement

#862 Fix chart colors
  packages/core/demo/data/gauge.ts
  packages/core/src/charts/gauge.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/graphs/bar-grouped.ts
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/components/graphs/gauge.ts
  packages/core/src/components/graphs/radar.ts
  packages/core/src/model-gauge.ts
  packages/core/src/styles/colors.scss
Labels: bug 🐛

#865 improvement(core): log an error to the console if CSS styles haven't been imported
  packages/core/src/services/essentials/dom-utils.ts
  packages/core/src/styles/_chart-holder.scss
Labels: enhancement

#876 fix(core): replace import to lodash with lodash-es
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/tools.ts
Labels: bug 🐛

#877 feat(core): add alignment options for gauge charts
  packages/core/src/components/graphs/gauge.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
Labels: enhancement

#858 Set toolbar control background to transparent
  packages/core/src/styles/components/_toolbar.scss
Labels: ui/ux ✨

#872 fix(core): only set zoombar data and sanitize date values if a cartes…
  packages/core/src/model-cartesian-charts.ts
  packages/core/src/model.ts
Labels: bug 🐛

#873 fix(core): correct axis title paddings in y-axes
  packages/core/src/components/axes/two-dimensional-axes.ts
Labels: bug 🐛

#719 add treemap graph
  packages/angular/src/charts.module.ts
  packages/angular/src/index.ts
  packages/angular/src/treemap-chart.component.ts
  packages/core/CHANGELOG.md
  packages/core/demo/data/index.ts
  packages/core/demo/data/treemap.ts
  packages/core/demo/styles.scss
  packages/core/package.json
  packages/core/src/charts/index.ts
  packages/core/src/charts/treemap.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/components/graphs/gauge.ts
  packages/core/src/components/graphs/radar.ts
  packages/core/src/components/graphs/treemap.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/events.ts
  packages/core/src/model-gauge.ts
  packages/core/src/services/essentials/dom-utils.ts
  packages/core/src/styles/graphs/_treemap.scss
  packages/core/src/styles/graphs/index.scss
  packages/core/stories/utils.ts
  packages/react/src/index.js
  packages/react/src/treemap-chart.js
  packages/svelte/src/TreemapChart.svelte
  packages/svelte/src/index.js
  packages/vue/CHANGELOG.md
  packages/vue/src/ccv-treemap-chart.vue
  packages/vue/src/index.js
  yarn-offline-mirror-cache/@carbon-colors-10.15.0.tgz
  yarn-offline-mirror-cache/@carbon-colors-10.4.0.tgz
  yarn.lock
Labels: Requested Component 🙏, design-approved ✅, enhancement

#888 fix(core): sanitize user provided axis domains
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#882 update charts when switching themes
  packages/core/stories/utils.ts
Labels: bug 🐛, demos

#734 Combo chart
  packages/angular/src/charts.module.ts
  packages/angular/src/combo-chart.component.ts
  packages/angular/src/index.ts
  packages/core/demo/data/area.ts
  packages/core/demo/data/bubble.ts
  packages/core/demo/data/combo.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/demo/data/scatter.ts
  packages/core/demo/data/zoom-bar.ts
  packages/core/src/axis-chart.ts
  packages/core/src/charts/area-stacked.ts
  packages/core/src/charts/bar-stacked.ts
  packages/core/src/charts/combo.ts
  packages/core/src/charts/index.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/grid.ts
  packages/core/src/components/axes/ruler-stacked.ts
  packages/core/src/components/axes/ruler.ts
  packages/core/src/components/axes/toolbar.ts
  packages/core/src/components/axes/two-dimensional-axes.ts
  packages/core/src/components/axes/zero-line.ts
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/components/component.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/threshold.ts
  packages/core/src/components/essentials/title-meter.ts
  packages/core/src/components/essentials/title.ts
  packages/core/src/components/essentials/tooltip-axis.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/components/graphs/area-stacked.ts
  packages/core/src/components/graphs/area.ts
  packages/core/src/components/graphs/bar-grouped.ts
  packages/core/src/components/graphs/bar-simple.ts
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/components/graphs/bar.ts
  packages/core/src/components/graphs/bubble.ts
  packages/core/src/components/graphs/donut.ts
  packages/core/src/components/graphs/gauge.ts
  packages/core/src/components/graphs/line.ts
  packages/core/src/components/graphs/meter.ts
  packages/core/src/components/graphs/pie.ts
  packages/core/src/components/graphs/radar.ts
  packages/core/src/components/graphs/scatter-stacked.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/components/graphs/skeleton-lines.ts
  packages/core/src/components/graphs/skeleton.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/model.ts
  packages/core/src/services/essentials/dom-utils.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/tools.ts
  packages/react/src/combo-chart.js
  packages/react/src/index.js
  packages/vue/src/ccv-combo-chart.vue
  packages/vue/src/index.js
Labels: Requested Component 🙏, enhancement

#893 feat(core): smoother transitions in grouped and stacked bar charts
  packages/core/src/components/graphs/bar-grouped.ts
  packages/core/src/components/graphs/bar-stacked.ts
Labels: enhancement

#820 feat(core): add lollipop graph
  packages/angular/src/charts.module.ts
  packages/angular/src/index.ts
  packages/angular/src/lollipop-chart.component.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/lollipop.ts
  packages/core/demo/data/step.ts
  packages/core/src/charts/index.ts
  packages/core/src/charts/lollipop.ts
  packages/core/src/components/graphs/bubble.ts
  packages/core/src/components/graphs/lollipop.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/react/src/index.ts
  packages/react/src/lollipop-chart.tsx
  packages/svelte/src/LollipopChart.svelte
  packages/svelte/src/index.js
  packages/vue/src/ccv-lollipop-chart.vue
  packages/vue/src/index.js
Labels: enhancement
