Repository carbon-design-system/carbon-charts, pull requests merged in 2020-10, with the labels that each got.

#826 feat(core): allow custom labels for total & group in tooltips
  packages/core/src/components/essentials/tooltip-axis.ts
  packages/core/src/interfaces/components.ts
Labels: accessibility, enhancement

#825 fix(core): take options.bars.width into account
  packages/core/src/components/graphs/bar.ts
Labels: bug 🐛

#829 fix(core): fix division by zero & timescale issues
  packages/core/src/components/graphs/scatter-stacked.ts
  packages/core/src/model.ts
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#832 fix(core): fix a11y issues with aria-labels & checkboxes
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/graphs/bar-grouped.ts
  packages/core/src/components/graphs/bar-stacked.ts
Labels: accessibility, bug 🐛

#834 fix(core): fix Legend and Tooltip group color
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/tooltip-axis.ts
Labels: bug 🐛

#836 fix(core): fix legend hover opacity results in radar graph
  packages/core/src/components/graphs/radar.ts
Labels: bug 🐛

#845 fix(core): pass all data to customHTML for scatter-stacked charts
  packages/core/src/components/graphs/scatter-stacked.ts
Labels: bug 🐛

#791 Toolbar
  packages/core/demo/data/index.ts
  packages/core/demo/data/toolbar.ts
  packages/core/src/axis-chart.ts
  packages/core/src/components/axes/toolbar.ts
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/components/essentials/title.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/a11y.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/interfaces/events.ts
  packages/core/src/services/zoom.ts
  packages/core/src/styles/components/_toolbar.scss
  packages/core/src/styles/components/index.scss
Labels: enhancement

#847 Tutorial - color palette
  packages/core/demo/styles.scss
  packages/core/stories/tutorials.stories.ts
  packages/core/stories/tutorials/color-palette.ts
  packages/core/stories/tutorials/index.ts
  packages/core/stories/tutorials/tabular-data-format.ts
Labels: documentation 📖

#854 fix Bubble stroke
  packages/core/src/components/graphs/bubble.ts
Labels: bug 🐛

#776 Loading and locked option for zoom bar
  packages/core/demo/data/index.ts
  packages/core/demo/data/zoom-bar.ts
  packages/core/src/axis-chart.ts
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/services/zoom.ts
Labels: enhancement
