Repository carbon-design-system/carbon-charts, pull requests merged in 2020-08, with the labels that each got.

#732 fix: fix tooltip position with zoom bar enabled
  packages/core/src/components/essentials/tooltip.ts
Labels: bug 🐛

#737 fix: use enter().append() instead of join()
  packages/core/src/components/axes/zoom-bar.ts
Labels: bug 🐛

#739 add slider view to zoombar
  packages/core/CHANGELOG.md
  packages/core/demo/data/zoom-bar.ts
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/styles/components/_zoom-bar.scss
  packages/vue/CHANGELOG.md
Labels: enhancement

#728 Add legend order option
  packages/core/demo/data/bar.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/model.ts
Labels: enhancement

#744 feat(svelte): add Meter chart wrapper
  packages/svelte/src/MeterChart.svelte
  packages/svelte/src/index.js
Labels: enhancement, svelte

#746 chore(monorepo): update logo
  README.md
  assets/logo.png
  assets/logo.svg
  packages/core/.storybook/assets/logo.png
  packages/core/.storybook/assets/logo.svg
  packages/core/demo/styles.scss
  packages/core/stories/all.stories.ts
Labels: design-approved ✅

#749 fix(core): separate out non-customizables in configuration.ts
  packages/core/CHANGELOG.md
  packages/core/demo/data/index.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/grid.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/title-meter.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/components/graphs/pie.ts
  packages/core/src/components/graphs/radar.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/model.ts
  packages/vue/CHANGELOG.md
Labels: enhancement

#759 feat: change zoom bar handle cursor to ew-resize
  packages/core/src/components/axes/zoom-bar.ts
Labels: design-approved ✅
