Repository carbon-design-system/carbon-charts, pull requests merged in 2020-06, with the labels that each got.

#654 fix(core, angular, react, vue, svelte): fix scatter graph data updates
  packages/core/src/components/graphs/scatter.ts
Labels: bug 🐛

#656 chore(core, react, angular, vue, svelte): update demo data
  packages/angular/stories/all.stories.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/radar.ts
  packages/react/stories/all.stories.js
  packages/svelte/stories/all.stories.js
  packages/vue/stories/all.stories.js
Labels: demos

#659 chore(core, react, angular, vue, svelte): fix codesandbox examples
  packages/angular/README.md
  packages/core/README.md
  packages/core/demo/create-codesandbox.ts
  packages/core/stories/tutorials/getting-started/angular.ts
  packages/core/stories/tutorials/getting-started/react.ts
  packages/core/stories/tutorials/getting-started/vanilla.ts
  packages/core/stories/tutorials/getting-started/vue.ts
  packages/react/README.md
  packages/svelte/README.md
  packages/vue/README.md
Labels: bug 🐛, demos

#666 Fix charts render data outside custom domain
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/src/model.ts
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#669 fix: add missing timescale option in AxisOptions interface
  packages/core/src/interfaces/charts.ts
Labels: bug 🐛

#672 Fix AreaPercentageChart domain issue
  packages/core/demo/data/area.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/src/components/graphs/area-stacked.ts
  packages/core/src/components/graphs/line.ts
  packages/core/src/components/graphs/scatter-stacked.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/interfaces/axis-scales.ts
  packages/core/src/model.ts
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#623 Gauge
  packages/angular/src/charts.module.ts
  packages/angular/src/gauge-chart.component.ts
  packages/angular/src/index.ts
  packages/core/demo/data/area.ts
  packages/core/demo/data/donut.ts
  packages/core/demo/data/gauge.ts
  packages/core/demo/data/index.ts
  packages/core/src/chart.ts
  packages/core/src/charts/gauge.ts
  packages/core/src/charts/index.ts
  packages/core/src/components/graphs/gauge.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/interfaces/events.ts
  packages/core/src/styles/graphs/_gauge.scss
  packages/core/src/styles/graphs/index.scss
  packages/core/stories/all.stories.ts
  packages/react/src/gauge-chart.js
  packages/react/src/index.js
  packages/vue/src/ccv-gauge-chart.vue
  packages/vue/src/index.js
Labels: Requested Component 🙏, enhancement

#680 fix(core): fix gauge charts without a delta number
  packages/core/src/components/graphs/gauge.ts
Labels: bug 🐛

#646 truncate label if too long to avoid graph display issue
  packages/core/demo/data/bar.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/demo/data/scatter.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/tooltip-bar.ts
  packages/core/src/components/essentials/tooltip-pie.ts
  packages/core/src/components/essentials/tooltip-radar.ts
  packages/core/src/components/essentials/tooltip-scatter.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/axis-scales.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/interfaces/truncation.ts
  packages/core/src/styles/components/_tooltip.scss
  packages/core/src/tools.ts
Labels: accessibility, enhancement

#681 Fix stacked area chart with uneven data
  packages/core/demo/data/area.ts
  packages/core/demo/data/index.ts
  packages/core/src/model.ts
Labels: bug 🐛

#682 fix(core): add tooltip to gauge chart
  packages/core/src/charts/gauge.ts
Labels: bug 🐛

#678 fix(core): stroke dissappears when remapping the dimensions
  packages/core/src/components/graphs/area-stacked.ts
  packages/core/src/components/graphs/line.ts
  packages/core/src/components/graphs/scatter-stacked.ts
Labels: bug 🐛
