Repository carbon-design-system/carbon-charts, pull requests merged in 2020-04, with the labels that each got.

#529 Tabular data format support
  packages/core/demo/data/bar.ts
  packages/core/demo/data/bubble.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/demo/data/pie.ts
  packages/core/demo/data/scatter.ts
  packages/core/demo/data/time-series-axis.ts
  packages/core/demo/styles.scss
  packages/core/package.json
  packages/core/src/charts/bar-grouped.ts
  packages/core/src/charts/bar-simple.ts
  packages/core/src/charts/donut.ts
  packages/core/src/charts/pie.ts
  packages/core/src/components/axes/grid.ts
  packages/core/src/components/essentials/legend.spec.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/tooltip-bar.ts
  packages/core/src/components/essentials/tooltip-pie.ts
  packages/core/src/components/essentials/tooltip-scatter.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/components/graphs/bar-grouped.ts
  packages/core/src/components/graphs/bar-simple.ts
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/components/graphs/bubble.ts
  packages/core/src/components/graphs/donut.ts
  packages/core/src/components/graphs/line.ts
  packages/core/src/components/graphs/pie.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/axis-scales.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/model-pie.ts
  packages/core/src/model-simple-bar.ts
  packages/core/src/model.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/tools.spec.ts
  packages/core/src/tools.ts
  packages/core/stories/tutorials.stories.ts
  yarn-offline-mirror-cache/marked-0.8.2.tgz
  yarn.lock
Labels: core, enhancement

#560 improvement(tools.ts): return 1 sig figure for pie/donut labels
  packages/core/src/tools.ts
Labels: accessibility, enhancement

#566 add "key" to stacked bar tooltip data
  packages/core/src/components/graphs/bar-stacked.ts
Labels: enhancement

#556 Pie zero labels
  packages/core/src/components/graphs/pie.ts
Labels: bug 🐛

#565 fix backwards compability issues with older data format
  packages/core/demo/styles.scss
  packages/core/src/components/graphs/donut.ts
  packages/core/src/model.ts
Labels: bug 🐛

#572 sanitize non-date input
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#574 optimize axis tick formatting
  packages/core/src/components/axes/axis.ts
Labels: bug 🐛

#586 fix line graph update issues
  packages/core/src/components/graphs/line.ts
Labels: bug 🐛

#584 Support for Horizontal Line and Scatter Chart
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/src/components/graphs/line.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/tools.ts
Labels: bug 🐛

#416 Code comments for tools.ts
  packages/core/src/tools.ts
Labels: documentation 📖

#588 Fix `Invalid time value` in Firefox
  packages/core/demo/data/index.ts
  packages/core/demo/data/time-series-axis.ts
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#595 remove bbox dependency on pie labels
  packages/core/src/components/graphs/pie.ts
Labels: bug 🐛

#593 fix scatter interface
  packages/core/src/interfaces/charts.ts
Labels: bug 🐛

#499 Ruler interaction replacing Grid mouse listeners for comparative tooltips
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/src/charts/bubble.ts
  packages/core/src/charts/line.ts
  packages/core/src/charts/scatter.ts
  packages/core/src/components/axes/grid.ts
  packages/core/src/components/axes/ruler.ts
  packages/core/src/components/graphs/bubble.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/styles/components/_ruler.scss
  packages/core/src/styles/components/index.scss
  packages/core/src/tools.ts
Labels: accessibility
