Repository carbon-design-system/carbon-charts, pull requests merged in 2021-01, with the labels that each got.

#919 Fix area color
  packages/core/src/components/graphs/area.ts
Labels: bug 🐛

#909 fix: set definedZoomBarData to zoom bar data
  packages/core/src/model-cartesian-charts.ts
Labels: bug 🐛

#844 feat(confidence interval component): implement confidence interval ch…
  packages/core/demo/data/area.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/graphs/area.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/services/scales-cartesian.ts
  packages/react/src/index.ts
Labels: enhancement

#910 Add area chart skeleton
  packages/core/demo/data/area.ts
  packages/core/demo/data/index.ts
  packages/core/src/charts/area-stacked.ts
  packages/core/src/charts/area.ts
Labels: bug 🐛

#891 Dual axes tutorial
  packages/core/stories/tutorials/combo-charts.ts
  packages/core/stories/tutorials/dual-axes.ts
  packages/core/stories/tutorials/index.ts
Labels: documentation 📖

#929 fix(core): add number to the donut center interface
  packages/core/src/interfaces/charts.ts
Labels: bug 🐛, core

#930 fix(core): update stacked groups for stacked charts on data updates
  packages/core/src/components/graphs/area-stacked.ts
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/model.ts
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#933 fix(@carbon/charts): fix issues with the filled flag being undefined in bubble charts
  packages/core/src/configuration.ts
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#924 fix(types): add peak, status properties to MeterChartOptions interface
  packages/core/src/interfaces/charts.ts
  packages/react/carbon__charts-react-tests.tsx
Labels: core

#932 chore(core): update highlight.js version
  packages/core/package.json
  packages/core/stories/tutorials.stories.ts
  yarn-offline-mirror-cache/highlight.js-10.5.0.tgz
  yarn.lock
Labels: build-process, core

#923 donut/pie fix spacing for 0 value slices
  packages/core/src/components/graphs/pie.ts
Labels: bug 🐛

#911 fix(core): use new object to avoid always true in object comparison
  packages/core/src/components/axes/zoom-bar.ts
Labels: bug 🐛

#934 fix: scatter color fill
  packages/core/src/components/graphs/scatter.ts
Labels: bug 🐛

#935 fix(demos): add stacked flag on combo chart demo option
  packages/core/demo/data/combo.ts
Labels: bug 🐛, demos

#936 style(lollipop): add stroke weight interaction on hover
  packages/core/CHANGELOG.md
  packages/core/demo/data/combo.ts
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/components/graphs/lollipop.ts
  packages/core/src/components/graphs/pie.ts
  packages/core/src/components/graphs/scatter.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/configuration.ts
  packages/core/src/styles/graphs/_lollipop.scss
  packages/core/src/styles/graphs/index.scss
  packages/react/CHANGELOG.md
  packages/react/carbon__charts-react-tests.tsx
  packages/vue/CHANGELOG.md
Labels: design-approved ✅, enhancement
