Repository carbon-design-system/carbon-charts, pull requests merged in 2021-07, with the labels that each got.

#1061 fix(core): correctly display negative values
  packages/core/src/components/graphs/radar.ts
Labels: bug 🐛

#1065 fix(core): check to see if data values meet log scale type requirements
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/src/services/scales-cartesian.ts
Labels: enhancement

#1066 fix(core): update area chart event enums to use the scatter enums
  packages/core/src/interfaces/events.ts
Labels: bug 🐛

#1067 build(core): add dom-to-image as a dependency
  packages/core/package.json
Labels: bug 🐛, dependencies

#1068 ci(monorepo): update github release workflow
  .github/workflows/release.yml
Labels: build-process, release

#1073 fix(core): make sure document exists in case using SSR
  packages/core/src/configuration.ts
Labels: bug 🐛, release

#1074 trigger release
  CHANGELOG.md
Labels: trigger-release

#1075 docs(svelte): add carbon-components styles to sandboxes
  packages/core/demo/create-codesandbox.ts
Labels: trigger-release

#1076 docs(svelte): update sandbox styling to support image exports
  packages/core/demo/create-codesandbox.ts
Labels: bug 🐛, demos, svelte, trigger-release

#1077 docs(tutorials): event name should be "bar-mouseover"
  packages/core/stories/tutorials/api.ts
  packages/core/stories/tutorials/event-listeners.ts
Labels: documentation 📖, trigger-release

#1078 fix(core): remove references to `process` in UMD bundles
  packages/core/package.json
  packages/core/rollup.config.js
  yarn-offline-mirror-cache/@rollup-plugin-replace-3.0.0.tgz
  yarn-offline-mirror-cache/@rollup-pluginutils-3.1.0.tgz
  yarn-offline-mirror-cache/magic-string-0.25.7.tgz
  yarn-offline-mirror-cache/picomatch-2.3.0.tgz
  yarn.lock
Labels: build-process, core, trigger-release

#1080 trigger release
  CHANGELOG.md
Labels: trigger-release

#1081 update modal z-index
  packages/core/src/styles/components/_modal.scss
Labels: accessibility, trigger-release

#1083 fix(core): gauge delta arrow not showing on first render
  packages/core/src/components/graphs/gauge.ts
Labels: bug 🐛, core, trigger-release

#1079 Rehaul Svelte documentation to focus on vite-powered set-ups
  packages/svelte/README.md
  packages/svelte/package.json
Labels: documentation 📖, svelte

#1086 fix(core): eliminate style conflicts with carbon-components
  packages/core/src/components/essentials/modal.ts
  packages/core/src/styles/components/_modal.scss
  packages/core/src/styles/components/_toolbar.scss
Labels: bug 🐛, core, ui/ux ✨

#1095 fix(core): avoid adding carbon css-reset to styles
  packages/core/src/styles/styles.scss
Labels: bug 🐛, core
