Repository carbon-design-system/carbon-charts, pull requests merged in 2021-08, with the labels that each got.

#1096 fix(core): set $css--default-type to false in the styles
  packages/core/src/styles/styles.scss
Labels: bug 🐛

#1097 fix(core): optimize fullscreen logic
  packages/core/src/services/essentials/dom-utils.ts
Labels: bug 🐛

#1099 update react peerDep values
  packages/react/package.json
Labels: bug 🐛, dependencies, react

#1100 ci(monorepo): update github workflows to use node 14
  .github/workflows/release.yml
Labels: build-process

#1103 build(svelte): update svelte dependencies to fix builds in node 14
  .github/workflows/release.yml
  packages/svelte/package.json
  yarn-offline-mirror-cache/jest-worker-26.6.2.tgz
  yarn-offline-mirror-cache/mri-1.1.6.tgz
  yarn-offline-mirror-cache/rollup-plugin-svelte-5.2.1.tgz
  yarn-offline-mirror-cache/rollup-plugin-svelte-7.1.0.tgz
  yarn-offline-mirror-cache/rollup-plugin-terser-7.0.2.tgz
  yarn-offline-mirror-cache/sade-1.7.4.tgz
  yarn-offline-mirror-cache/serialize-javascript-4.0.0.tgz
  yarn-offline-mirror-cache/source-map-support-0.5.19.tgz
  yarn-offline-mirror-cache/svelte-3.31.2.tgz
  yarn-offline-mirror-cache/svelte-3.42.1.tgz
  yarn-offline-mirror-cache/svelte-check-1.1.26.tgz
  yarn-offline-mirror-cache/svelte-check-2.2.4.tgz
  yarn-offline-mirror-cache/svelte-dev-helper-1.1.9.tgz
  yarn-offline-mirror-cache/svelte-loader-2.13.6.tgz
  yarn-offline-mirror-cache/terser-5.7.1.tgz
  yarn.lock
Labels: bug 🐛, build-process, dependencies, svelte

#1104 docs(codesandbox): update d3 version to 7.0.0
  packages/core/demo/create-codesandbox.ts
Labels: bug 🐛, demos

#1108 build(svelte): fix storybook build
  packages/svelte/package.json
  yarn-offline-mirror-cache/svelte-dev-helper-1.1.9.tgz
  yarn-offline-mirror-cache/svelte-loader-2.13.6.tgz
  yarn.lock
Labels: bug 🐛, build-process, svelte

#1114 fix(angular): remove .ts from the area chart export
  packages/angular/src/index.ts
Labels: bug 🐛, angular

#1120 feat(core): remove backgrounds on chart holder & wrapper
  packages/core/src/services/essentials/dom-utils.ts
  packages/core/src/styles/_chart-holder.scss
Labels: bug 🐛, design-approved ✅

#1121 feat(core): support negative values in stacked bar
  packages/core/demo/data/bar.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/src/charts/bar-stacked.ts
  packages/core/src/charts/line.ts
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/model/model.ts
  packages/core/src/services/scales-cartesian.ts
Labels: enhancement, design-approved ✅

#1124 docs(all): remove references to d3v5.x
  packages/angular/README.md
  packages/core/README.md
  packages/react/README.md
  packages/svelte/README.md
  packages/vue/README.md
Labels: documentation 📖

#1125 Update READMEs
  packages/angular/README.md
  packages/core/README.md
  packages/react/README.md
  packages/svelte/README.md
  packages/vue/README.md
Labels: documentation 📖

#1126 docs(all): update d3 version in sandbox demos
  packages/core/demo/create-codesandbox.ts
Labels: bug 🐛, demos

#1127 fix(core): display correct toolbar controls based on provided options
  packages/core/src/tools.ts
Labels: bug 🐛
