Repository carbon-design-system/carbon-charts, pull requests merged in 2021-09, with the labels that each got.

#1116 feat(core): add tree chart
  packages/angular/src/charts.module.ts
  packages/angular/src/index.ts
  packages/angular/src/tree-chart.component.ts
  packages/core/demo/data/CHART_TYPES.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/tree.ts
  packages/core/src/chart.ts
  packages/core/src/charts/index.ts
  packages/core/src/charts/meter.ts
  packages/core/src/charts/tree.ts
  packages/core/src/components/graphs/pie.ts
  packages/core/src/components/graphs/tree.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/interfaces/events.ts
  packages/core/src/styles/graphs/_tree.scss
  packages/core/src/styles/graphs/index.scss
  packages/core/stories/all.stories.ts
  packages/core/stories/utils.ts
  packages/react/src/index.ts
  packages/react/src/tree-chart.tsx
  packages/svelte/src/TreeChart.svelte
  packages/svelte/src/index.js
  packages/vue/src/ccv-tree-chart.vue
  packages/vue/src/index.js
Labels: enhancement, design-approved ✅

#1048 feat(highlight): Add highlights
  packages/core/demo/data/area.ts
  packages/core/demo/data/index.ts
  packages/core/src/axis-chart.ts
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/components/essentials/highlights.ts
  packages/core/src/components/index.ts
  packages/core/src/styles/components/_highlights.scss
  packages/core/src/styles/components/_zoom-bar.scss
  packages/core/src/styles/components/index.scss
Labels: enhancement, design-approved ✅

#1147 fix(core): display donut-figure in the center when donut-title is empty
  packages/core/src/components/graphs/donut.ts
Labels: enhancement

#1134 fix(core): render empty zoom bar holder when there is 1 data point
  packages/core/src/components/axes/zoom-bar.ts
Labels: bug 🐛

#1150 fix(core): diagram rendering issues in safari
  packages/angular/src/diagrams/card-node/card-node.component.ts
  packages/angular/src/diagrams/shape-node/shape-node.component.ts
  packages/angular/stories/diagrams/0_diagram.stories.ts
  packages/angular/stories/diagrams/shape-node.stories.ts
  packages/core/src/styles/components/diagrams/_edge.scss
  packages/react/src/diagrams/CardNode/CardNode.tsx
  packages/react/src/diagrams/ShapeNode/ShapeNode.tsx
  packages/react/stories/diagrams/0_Diagrams.stories.js
  packages/react/stories/diagrams/ShapeNode.stories.js
Labels: bug 🐛, core

#1151 fix(core): legend alignment incorrect initial rendering
  packages/core/src/components/essentials/legend.ts
  packages/core/src/styles/components/_legend.scss
Labels: bug 🐛, core

#1132 feat(core): create alluvial chart
  packages/angular/src/alluvial-chart.component.ts
  packages/angular/src/charts.module.ts
  packages/angular/src/index.ts
  packages/core/demo/data/CHART_TYPES.ts
  packages/core/demo/data/alluvial.ts
  packages/core/demo/data/index.ts
  packages/core/package.json
  packages/core/src/charts/alluvial.ts
  packages/core/src/charts/index.ts
  packages/core/src/components/graphs/alluvial.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/events.ts
  packages/core/src/styles/graphs/_alluvial.scss
  packages/core/src/styles/graphs/index.scss
  packages/react/src/alluvial-chart.tsx
  packages/react/src/index.ts
  packages/svelte/src/AlluvialChart.svelte
  packages/svelte/src/index.js
  packages/vue/src/ccv-alluvial-chart.vue
  packages/vue/src/index.js
  yarn-offline-mirror-cache/d3-array-2.12.1.tgz
  yarn-offline-mirror-cache/d3-path-1.0.9.tgz
  yarn-offline-mirror-cache/d3-shape-1.3.7.tgz
  yarn-offline-mirror-cache/internmap-1.0.1.tgz
  yarn.lock
Labels: design-approved ✅, Requested Component 🙏, new charts 📊

#1156 fix(core): groupMapsTo in stacked bar charts
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/model/model.ts
  yarn-offline-mirror-cache/d3-sankey-0.12.3.tgz
Labels: bug 🐛

#1163 fix(core): replace empty hyperlink with an appropriate tag
  packages/core/src/components/essentials/tooltip.ts
Labels: bug 🐛, accessibility

#1165 fix(core): stacked layouts in combo charts
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#1164 chore(monorepo): update meta tags
  packages/angular/.storybook/assets/favicon.ico
  packages/angular/.storybook/assets/logo.svg
  packages/angular/.storybook/assets/share.png
  packages/angular/.storybook/manager-head.html
  packages/angular/package.json
  packages/core/.storybook/assets/favicon.ico
  packages/core/.storybook/assets/share.png
  packages/core/.storybook/manager-head.html
  packages/react/.storybook/assets/logo.svg
  packages/react/.storybook/assets/share.png
  packages/react/.storybook/manager-head.html
  packages/react/assets/favicon.ico
  packages/react/package.json
  packages/svelte/.storybook/assets/logo.svg
  packages/svelte/.storybook/assets/share.png
  packages/svelte/.storybook/manager-head.html
  packages/svelte/package.json
  packages/vue/.storybook/assets/logo.svg
  packages/vue/.storybook/assets/share.png
  packages/vue/.storybook/manager-head.html
  packages/vue/package.json
  scripts/build-demos.sh
  scripts/build-packages-and-demos.sh
Labels: demos

#1159 fix(core): correctly draw the threshold from multiple axes
  packages/core/src/components/essentials/threshold.ts
Labels: bug 🐛
