Repository carbon-design-system/carbon-charts, pull requests merged in 2021-03, with the labels that each got.

#965 fix(meter): meter update bug
  packages/core/src/components/graphs/meter.ts
Labels: bug 🐛

#970 Stop casting of null values in data to numbers
  packages/core/demo/data/line.ts
  packages/core/src/model.ts
Labels: bug 🐛

#942 feat(gauge): added hideSymbol property to gauge to prevent display of…
  packages/core/src/components/graphs/gauge.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
Labels: enhancement

#974 chore(demos): re-organize demos
  packages/core/demo/data/index.ts
  packages/core/demo/data/toolbar.ts
Labels: demos

#975 improvement(core): optimize valueFormatter logic in tooltips
  packages/core/src/components/essentials/tooltip-axis.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/configuration.ts
Labels: enhancement

#979 fix(core): fix issues with zeroes in scale bounds
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#977 improvement(configuration for gridline/tick alignment)
  packages/core/CHANGELOG.md
  packages/core/src/components/axes/grid.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/components.ts
  packages/react/CHANGELOG.md
  packages/vue/CHANGELOG.md
Labels: enhancement

#985 fix(bounded area chart): update bounded area chart so bounds don't sh…
  packages/core/src/components/graphs/area.ts
Labels: bug 🐛

#987 docs(update demos): remove exp flag and re-add guage/lollipop demos
  packages/core/demo/data/combo.ts
  packages/core/demo/data/index.ts
Labels: demos
