Repository carbon-design-system/carbon-charts, pull requests merged in 2021-04, with the labels that each got.

#990 Add ^11.0.0 to angular peerDependencies
  packages/angular/package.json
Labels: angular, dependencies

#991 fix(tooltip): tooltip discarding 0 values
  packages/core/CHANGELOG.md
  packages/core/src/components/essentials/tooltip.ts
  packages/react/CHANGELOG.md
  packages/vue/CHANGELOG.md
Labels: bug 🐛

#992 Demos reorg
  packages/angular/.storybook/config.js
  packages/angular/stories/all.stories.ts
  packages/core/demo/data/CHART_TYPES.ts
  packages/core/demo/data/area.ts
  packages/core/demo/data/bar.ts
  packages/core/demo/data/boxplot.ts
  packages/core/demo/data/combo.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/demo/data/scatter.ts
  packages/core/demo/styles.scss
  packages/core/src/model.ts
  packages/core/src/tools.ts
  packages/core/stories/all.stories.ts
  packages/core/stories/tutorials.stories.ts
  packages/react/.storybook/config.js
  packages/react/stories/all.stories.js
  packages/svelte/.storybook/config.js
  packages/svelte/src/BaseChart.svelte
  packages/svelte/stories/all.stories.js
  packages/vue/.storybook/config.js
  packages/vue/stories/all.stories.js
Labels: demos

#993 docs(demos): separate out area demos
  packages/core/demo/data/area.ts
  packages/core/demo/data/index.ts
Labels: demos

#994 fix(core): fix sizing issues with the legend component
  packages/core/demo/styles.scss
  packages/core/src/components/layout/layout.ts
  packages/core/stories/all.stories.ts
Labels: bug 🐛

#998 fix(wordcloud): fix render issues in firefox & add getFillColor()
  packages/core/src/components/graphs/wordcloud.ts
  packages/core/src/interfaces/charts.ts
Labels: bug 🐛

#1000 fix(legend): vertical alignment
  packages/core/CHANGELOG.md
  packages/core/demo/data/area.ts
  packages/core/demo/data/index.ts
  packages/core/demo/data/line.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/tools.ts
  packages/react/CHANGELOG.md
  packages/react/stories/all.stories.js
  packages/vue/CHANGELOG.md
  packages/vue/stories/all.stories.js
Labels: bug 🐛

#976 feat(core): floating bars
  packages/core/demo/data/bar.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/essentials/tooltip-axis.ts
  packages/core/src/components/graphs/bar-simple.ts
  packages/core/src/services/scales-cartesian.ts
Labels: enhancement

#969 feat(core): add bullet graph
  packages/angular/src/bullet-chart.component.ts
  packages/angular/src/charts.module.ts
  packages/angular/src/index.ts
  packages/core/CHANGELOG.md
  packages/core/demo/data/CHART_TYPES.ts
  packages/core/demo/data/bullet.ts
  packages/core/demo/data/index.ts
  packages/core/src/axis-chart.ts
  packages/core/src/chart.ts
  packages/core/src/charts/bullet.ts
  packages/core/src/charts/index.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/grid.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/graphs/bubble.ts
  packages/core/src/components/graphs/bullet.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/axis-scales.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/styles/colors.scss
  packages/core/src/styles/graphs/_bullet.scss
  packages/core/src/styles/graphs/index.scss
  packages/react/CHANGELOG.md
  packages/react/src/bullet-chart.tsx
  packages/react/src/index.ts
  packages/svelte/src/BulletChart.svelte
  packages/svelte/src/index.js
  packages/svelte/stories/ChartWrapper.svelte
  packages/vue/src/ccv-bullet-chart.vue
  packages/vue/src/index.js
Labels: enhancement

#1007 fix(core): fix minor bug with data values that are undefined
  packages/core/CHANGELOG.md
  packages/core/src/components/essentials/tooltip-axis.ts
  packages/core/src/components/graphs/area-stacked.ts
  packages/core/src/components/graphs/area.ts
  packages/core/src/components/graphs/bar-simple.ts
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/components/graphs/line.ts
  packages/core/src/components/graphs/scatter-stacked.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/services/scales-cartesian.ts
  packages/react/CHANGELOG.md
  packages/vue/CHANGELOG.md
Labels: bug 🐛

#1006 docs(demos): add code examples in the event listeners tutorial
  packages/core/stories/tutorials/event-listeners.ts
Labels: demos

#1005 updated font & styling for labels and titles
  packages/core/src/components/axes/axis.ts
  packages/core/src/styles/components/_axis.scss
Labels: accessibility, design-approved ✅, enhancement
