Repository carbon-design-system/carbon-charts, pull requests merged in 2021-02, with the labels that each got.

#943 chore(angular): whitelist carbon telemetry dependency for Angular CLI
  packages/angular/ng-package.json
  packages/angular/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/svelte/package.json
  packages/vue/CHANGELOG.md
  packages/vue/package.json
  scripts/add-telemetry-to-packages.js
  scripts/clean-package-jsons.js
  scripts/deploy.sh
Labels: build-process

#950 fix: Stacked area color
  packages/core/src/components/graphs/area-stacked.ts
  packages/core/src/components/graphs/area.ts
  packages/core/src/components/graphs/lollipop.ts
Labels: bug 🐛

#954 style(gauge): number formatting
  packages/core/CHANGELOG.md
  packages/core/src/components/graphs/gauge.ts
  packages/core/src/styles/_type.scss
  packages/react/CHANGELOG.md
  packages/vue/CHANGELOG.md
Labels: bug 🐛, ui/ux ✨

#957 improvement(time series): enhance month change logic
  packages/core/CHANGELOG.md
  packages/core/demo/data/combo.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/essentials/threshold.ts
  packages/core/src/services/time-series.ts
  packages/core/src/styles/components/_grid.scss
  packages/react/CHANGELOG.md
  packages/vue/CHANGELOG.md
Labels: bug 🐛

#927 pie/donut: disable labels (and callouts)
  packages/core/CHANGELOG.md
  packages/core/src/components/graphs/pie.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/react/CHANGELOG.md
  packages/vue/CHANGELOG.md
Labels: Requested Component 🙏

#958 feat(core): add boxplot chart
  packages/angular/src/boxplot-chart.component.ts
  packages/angular/src/charts.module.ts
  packages/angular/src/index.ts
  packages/core/CHANGELOG.md
  packages/core/demo/data/boxplot.ts
  packages/core/demo/data/index.ts
  packages/core/src/axis-chart.ts
  packages/core/src/charts/boxplot.ts
  packages/core/src/charts/index.ts
  packages/core/src/components/component.ts
  packages/core/src/components/graphs/boxplot.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/events.ts
  packages/core/src/model-boxplot.ts
  packages/core/src/model.ts
  packages/react/CHANGELOG.md
  packages/react/src/boxplot-chart.tsx
  packages/react/src/index.ts
  packages/svelte/src/BoxplotChart.svelte
  packages/svelte/src/index.js
  packages/vue/CHANGELOG.md
  packages/vue/src/ccv-boxplot-chart.vue
  packages/vue/src/index.js
Labels: Requested Component 🙏

#906 fix(combo chart): cleanup demos and bugs
  packages/core/CHANGELOG.md
  packages/core/demo/data/bubble.ts
  packages/core/demo/data/combo.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/interfaces/axis-scales.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/model.ts
  packages/react/CHANGELOG.md
Labels: enhancement

#959 fix(core): rewrite the thresholds rendering logic
  packages/core/CHANGELOG.md
  packages/core/src/axis-chart.ts
  packages/core/src/components/axes/two-dimensional-axes.ts
  packages/core/src/components/essentials/threshold.ts
  packages/core/src/styles/components/_threshold.scss
  packages/react/CHANGELOG.md
Labels: bug 🐛

#962 Stacked area bugfixes
  packages/core/src/components/axes/ruler-stacked.ts
  packages/core/src/components/graphs/area-stacked.ts
  packages/react/CHANGELOG.md
  packages/vue/CHANGELOG.md
Labels: bug 🐛

#964 fix(core): fix boxplot color
  packages/core/src/model-boxplot.ts
Labels: bug 🐛
