Repository carbon-design-system/carbon-charts, pull requests merged in 2021-10, with the labels that each got.

#1171 fix(styles): use `map-get` in `_type.scss`
  packages/core/src/styles/_type.scss
Labels: bug 🐛

#1174 docs(core): fix broken demo
  packages/core/demo/data/area.ts
  packages/core/demo/data/hightlight.ts
  packages/core/demo/data/index.ts
Labels: documentation 📖, demos

#1176 docs(storybook): update/add welcome stories
  packages/angular/.storybook/assets/welcome.png
  packages/angular/.storybook/config.js
  packages/angular/.storybook/manager-head.html
  packages/angular/.storybook/theme.js
  packages/angular/package.json
  packages/angular/stories/all.stories.ts
  packages/core/.storybook/assets/welcome.png
  packages/core/.storybook/config.js
  packages/core/.storybook/manager-head.html
  packages/core/demo/styles.scss
  packages/core/stories/all.stories.ts
  packages/react/.storybook/assets/welcome.png
  packages/react/.storybook/config.js
  packages/react/.storybook/manager-head.html
  packages/react/.storybook/theme.js
  packages/react/package.json
  packages/react/stories/all.stories.js
  packages/svelte/.storybook/assets/welcome.png
  packages/svelte/.storybook/manager-head.html
  packages/svelte/stories/Welcome.svelte
  packages/svelte/stories/all.stories.js
  packages/vue/.storybook/assets/welcome.png
  packages/vue/.storybook/manager-head.html
  packages/vue/package.json
  packages/vue/stories/all.stories.js
Labels: enhancement, documentation 📖, demos

#1178 fix(core): allow users to assign custom colors to the links of source nodes
  packages/core/demo/data/alluvial.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/graphs/alluvial.ts
Labels: enhancement
