Repository carbon-design-system/carbon-charts, pull requests merged in 2021-05, with the labels that each got.

#1010 fix(core): set a min-2px size for simple bars
  packages/core/src/components/graphs/bar-simple.ts
Labels: accessibility, bug 🐛, design-approved ✅

#1023 Update circle pack cursor styling
  packages/core/demo/data/index.ts
  packages/core/src/components/graphs/circle-pack.ts
  packages/core/src/styles/graphs/_circle-pack.scss
Labels: accessibility, enhancement, ui/ux ✨

#1028 chore(core): update lodash-es version
  packages/core/package.json
  yarn-offline-mirror-cache/lodash-es-4.17.15.tgz
  yarn-offline-mirror-cache/lodash-es-4.17.21.tgz
  yarn.lock
Labels: dependencies

#1035 fix(core): fix circlepacks with one dataset
  packages/core/src/components/graphs/circle-pack.ts
  packages/core/src/model-circle-pack.ts
Labels: bug 🐛

#1037 fix(core): make sure tooltips are properly positioned when closer to the edges
  packages/core/src/components/essentials/tooltip.ts
Labels: bug 🐛

#1036 fix(core): account for threshold values when determining scale domains
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛
