Repository carbon-design-system/carbon-charts, pull requests merged in 2021-11, with the labels that each got.

#1207 fix(core): render chart axis labels correctly when data loads async
  packages/core/src/services/angle-utils.ts
Labels: bug 🐛

#1208 fix(core): improve keyboard accessibility
  packages/core/src/components/axes/toolbar.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/modal.ts
Labels: bug 🐛, enhancement, accessibility

#1209 fix(core): remove direct reference to getBBox()
  packages/core/src/components/axes/axis.ts
Labels: bug 🐛

#1210 ci(monorepo): add sonarcloud workflow
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: enhancement, build-process

#1218 fix(svelte): remove default export in `index.html`
  packages/core/demo/create-codesandbox.ts
Labels: bug 🐛, demos, svelte

#1219 feat(svelte): add TypeScript definitions for Alluvial, Histogram, and Tree charts
  packages/svelte/tests/AlluvialChart.test.svelte
  packages/svelte/tests/HistogramChart.test.svelte
  packages/svelte/tests/TreeChart.test.svelte
  packages/svelte/types/AlluvialChart.d.ts
  packages/svelte/types/BaseChart.d.ts
  packages/svelte/types/HistogramChart.d.ts
  packages/svelte/types/TreeChart.d.ts
  packages/svelte/types/index.d.ts
Labels: enhancement, documentation 📖, svelte

#1220 fix(core): set pointer events of highlight elements to none
  packages/core/demo/data/hightlight.ts
  packages/core/src/styles/components/_highlights.scss
Labels: bug 🐛, accessibility

#1223 Remove sonarcloud
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: build-process

#1181 improvement(core): add peak to proportional meter
  packages/core/demo/data/index.ts
  packages/core/demo/data/meter.ts
  packages/core/src/components/essentials/title-meter.ts
  packages/core/src/components/graphs/meter.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/model/meter.ts
Labels: enhancement
