Repository carbon-design-system/carbon-charts, pull requests merged in 2021-06, with the labels that each got.

#1041 fix(core): radar animation issues, axis updates and zooming
  packages/core/src/components/graphs/radar.ts
Labels: bug 🐛

#1046 updated build process for diagram components
  packages/angular/src/components/diagrams/card-node/card-node.stories.ts
  packages/angular/src/components/diagrams/edge/edge.stories.ts
  packages/angular/src/components/diagrams/marker/marker.stories.ts
  packages/angular/src/components/diagrams/shape-node/shape-node.stories.ts
  packages/angular/src/diagrams/card-node/card-node-column.component.ts
  packages/angular/src/diagrams/card-node/card-node-label.component.ts
  packages/angular/src/diagrams/card-node/card-node-subtitle.component.ts
  packages/angular/src/diagrams/card-node/card-node-title.component.ts
  packages/angular/src/diagrams/card-node/card-node.component.ts
  packages/angular/src/diagrams/card-node/card-node.module.ts
  packages/angular/src/diagrams/edge/edge.component.ts
  packages/angular/src/diagrams/edge/edge.module.ts
  packages/angular/src/diagrams/marker/marker.component.ts
  packages/angular/src/diagrams/marker/marker.module.ts
  packages/angular/src/diagrams/shape-node/shape-node.component.ts
  packages/angular/src/diagrams/shape-node/shape-node.module.ts
  packages/angular/src/index.ts
  packages/angular/stories/diagrams/0_diagram.stories.ts
  packages/angular/stories/diagrams/card-node.stories.ts
  packages/angular/stories/diagrams/edge.stories.ts
  packages/angular/stories/diagrams/marker.stories.ts
  packages/angular/stories/diagrams/shape-node.stories.ts
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/core/src/styles/components/diagrams/_shape-node.scss
  packages/react/CHANGELOG.md
  packages/react/src/diagrams/CardNode/CardNode.tsx
  packages/react/src/diagrams/CardNode/CardNodeColumn.tsx
  packages/react/src/diagrams/CardNode/CardNodeLabel.tsx
  packages/react/src/diagrams/CardNode/CardNodeSubtitle.tsx
  packages/react/src/diagrams/CardNode/CardNodeTitle.tsx
  packages/react/src/diagrams/CardNode/index.tsx
  packages/react/src/diagrams/Edge/Edge.tsx
  packages/react/src/diagrams/Edge/index.tsx
  packages/react/src/diagrams/Marker/Marker.tsx
  packages/react/src/diagrams/Marker/index.tsx
  packages/react/src/diagrams/ShapeNode/ShapeNode.tsx
  packages/react/src/diagrams/ShapeNode/index.tsx
  packages/react/stories/diagrams/0_Diagrams.stories.js
  packages/react/stories/diagrams/CardNode.stories.js
  packages/react/stories/diagrams/Edge.stories.js
  packages/react/stories/diagrams/Marker.stories.js
  packages/react/stories/diagrams/ShapeNode.stories.js
  packages/vue/CHANGELOG.md
Labels: angular, core, react

#1049 feat(svelte): add type definitions for BulletChart, CirclePackChart
  packages/svelte/tests/BulletChart.test.svelte
  packages/svelte/tests/CirclePackChart.test.svelte
  packages/svelte/types/BulletChart.d.ts
  packages/svelte/types/CirclePackChart.d.ts
  packages/svelte/types/index.d.ts
Labels: svelte

#1050 fix(core): start bars at correct position when axis min is non-zero
  packages/core/src/components/graphs/bar-simple.ts
Labels: bug 🐛

#1043 feat(pie): add sortFunction option for pie chart
  packages/core/src/components/graphs/pie.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
Labels: core, enhancement

#1009 fix(core): fix bullet demo issue
  packages/core/demo/data/bullet.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/model-circle-pack.ts
  packages/core/src/tools.ts
Labels: bug 🐛

#1033 fix(core): fix custom color for circlepacks
  packages/core/CHANGELOG.md
  packages/core/demo/data/circle-pack.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/graphs/circle-pack.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/styles/graphs/_circle-pack.scss
  packages/react/CHANGELOG.md
  packages/vue/CHANGELOG.md
  yarn.lock
Labels: bug 🐛

#1052 Update diagram examples
  packages/angular/stories/diagrams/0_diagram.stories.ts
  packages/core/demo/styles.scss
  packages/react/stories/diagrams/0_Diagrams.stories.js
Labels: angular, demos, react

#1055 fix(core): keep custom fill colors if custom getIsFilled is passed
  packages/core/src/components/graphs/scatter.ts
Labels: bug 🐛

#1056 fix(core): display the correct total sum for circle pack
  packages/core/src/components/graphs/circle-pack.ts
Labels: bug 🐛

#1057 feat(angular): add angular 12 to peer dependencies
  packages/angular/package.json
Labels: angular
