Repository carbon-design-system/carbon-charts, pull requests merged in 2021-12, with the labels that each got.

#1230 fix: set zoom domain if old initial zoom domain is undefined
  packages/core/src/components/axes/zoom-bar.ts
Labels: bug 🐛

#1222 feat(react diagrams): add support for applying a custom class to the outer node
  packages/react/src/diagrams/CardNode/CardNode.tsx
  packages/react/src/diagrams/CardNode/CardNodeColumn.tsx
  packages/react/src/diagrams/CardNode/CardNodeLabel.tsx
  packages/react/src/diagrams/CardNode/CardNodeSubtitle.tsx
  packages/react/src/diagrams/CardNode/CardNodeTitle.tsx
  packages/react/src/diagrams/Edge/Edge.tsx
  packages/react/src/diagrams/Marker/Marker.tsx
  packages/react/src/diagrams/ShapeNode/ShapeNode.tsx
Labels: enhancement

#1233 fix(core): display the correct group when hovering over scatter point
  packages/core/src/model/model.ts
Labels: bug 🐛

#1236 fix(core): display respective combochart tooltips range label
  packages/core/src/components/essentials/tooltip-axis.ts
Labels: bug 🐛, accessibility

#1239 fix(core): fix overflow menu caused by data loading option change
  packages/core/src/components/axes/toolbar.ts
Labels: bug 🐛

#1243 fix(core): use domain in zoom bar if defined in axes
  packages/core/src/services/zoom.ts
Labels: bug 🐛

#1200 feat(core): create heatmap chart
  packages/angular/src/charts.module.ts
  packages/angular/src/heatmap-chart.component.ts
  packages/angular/src/index.ts
  packages/core/demo/data/CHART_TYPES.ts
  packages/core/demo/data/heatmap.ts
  packages/core/demo/data/index.ts
  packages/core/src/charts/heatmap.ts
  packages/core/src/charts/index.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/hover-axis.ts
  packages/core/src/components/axes/two-dimensional-axes.ts
  packages/core/src/components/essentials/color-scale-legend.ts
  packages/core/src/components/graphs/heatmap.ts
  packages/core/src/components/index.ts
  packages/core/src/configuration-non-customizable.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/components.ts
  packages/core/src/interfaces/enums.ts
  packages/core/src/interfaces/events.ts
  packages/core/src/model/cartesian-charts.ts
  packages/core/src/model/heatmap.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/styles/color-palatte.scss
  packages/core/src/styles/colors.scss
  packages/core/src/styles/components/_axis.scss
  packages/core/src/styles/components/_color-legend.scss
  packages/core/src/styles/components/index.scss
  packages/core/src/styles/graphs/_heatmap.scss
  packages/core/src/styles/graphs/index.scss
  packages/react/src/heatmap-chart.tsx
  packages/react/src/index.ts
  packages/svelte/src/HeatmapChart.svelte
  packages/svelte/src/index.js
  packages/vue/src/ccv-heatmap-chart.vue
  packages/vue/src/index.js
Labels: enhancement, Requested Component 🙏, new charts 📊
