Repository carbon-design-system/carbon-charts, pull requests merged in 2022-01, with the labels that each got.

#1260 fix(core): remove circular dependencies inheritance from heatmap legend & canvas zoom files
  packages/core/src/components/essentials/color-scale-legend.ts
  packages/core/src/services/canvas-zoom.ts
Labels: bug 🐛, demos

#1261 fix(core): add background to chart in fullscreen mode
  packages/core/src/styles/_chart-holder.scss
Labels: bug 🐛, accessibility, ui/ux ✨

#1235 fix(stacked-bar): set bar width based on number of domain values
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/model/model.ts
Labels: bug 🐛

#1263 fix(core): prevent area chart from bleeding out of cartesian plane when includeZero is enabled
  packages/core/src/components/graphs/area.ts
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#1249 fix(core): keep radar chart alignment after fullscreen exit
  packages/core/src/components/graphs/radar.ts
Labels: bug 🐛

#1257 add executable bit to shell scripts
  packages/angular/build.sh
  packages/core/build-vendor.sh
  packages/core/build.sh
  packages/react/build.sh
  packages/svelte/build.sh
  packages/vue/build.sh
Labels: build-process

#1245 docs(core): add floating line combo chart example in storybook
  packages/core/demo/data/combo.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/essentials/tooltip-axis.ts
Labels: documentation 📖, demos

#1267 fix(core): prevent chart from breaking if thresholds array is empty
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/styles/_chart-holder.scss
  packages/core/src/styles/components/_skeleton.scss
Labels: bug 🐛

#1274 docs(svelte): fix and update Rollup usage
  packages/svelte/README.md
Labels: documentation 📖, build-process

#1281 fix(core): position bounds correctly in secondary axis of combo chart
  packages/core/src/services/scales-cartesian.ts
Labels: bug 🐛

#1258 fix(build): svelte packaging
  packages/svelte/build.sh
  packages/svelte/package.json
  packages/svelte/rollup.config.js
Labels: bug 🐛, build-process

#1291 improvement(bars): add `spacingFactor` option
  packages/core/src/components/graphs/bar-stacked.ts
  packages/core/src/components/graphs/bar.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/components.ts
Labels: enhancement

#1289 fix(radar): only show active datapoints in tooltips
  packages/core/src/components/graphs/radar.ts
Labels: bug 🐛
