Repository carbon-design-system/carbon-charts, pull requests merged in 2022-03, with the labels that each got.

#1324 docs(carbon-platform): index charts with schema
  packages/angular/carbon.yml
  packages/core/carbon.yml
  packages/react/carbon.yml
  packages/svelte/carbon.yml
  packages/vue/carbon.yml
  thumbnails/alluvial.svg
  thumbnails/area-simple.svg
  thumbnails/area-stacked.svg
  thumbnails/bar-floating.svg
  thumbnails/bar-grouped.svg
  thumbnails/bar-horizontal.svg
  thumbnails/bar-simple.svg
  thumbnails/bar-stacked.svg
  thumbnails/boxplot.svg
  thumbnails/bubble.svg
  thumbnails/bullet.svg
  thumbnails/circle-pack.svg
  thumbnails/combo.svg
  thumbnails/donut.svg
  thumbnails/gauge.svg
  thumbnails/geo-choropleth.svg
  thumbnails/geo-connection.svg
  thumbnails/geo-proportion.svg
  thumbnails/heat-map.svg
  thumbnails/histogram.svg
  thumbnails/line.svg
  thumbnails/lollipop.svg
  thumbnails/meter-proportional.svg
  thumbnails/meter.svg
  thumbnails/network-diagram.svg
  thumbnails/parallel.svg
  thumbnails/pie.svg
  thumbnails/radar.svg
  thumbnails/scatter.svg
  thumbnails/sparkline.svg
  thumbnails/step.svg
  thumbnails/stream.svg
  thumbnails/tree-diagram.svg
  thumbnails/tree-map.svg
  thumbnails/word-cloud.svg
Labels: documentation 📖

#1325 fix(core): enable heatmap value domain to support small values
  packages/core/demo/data/heatmap.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/essentials/color-scale-legend.ts
  packages/core/src/model/heatmap.ts
Labels: bug 🐛

#1330 chore(core): update carbon telemetry version to 0.1.0
  packages/core/package.json
  yarn-offline-mirror-cache/@carbon-telemetry-0.1.0.tgz
  yarn.lock
Labels: dependencies

#1305 feat(core): add alignment option to alluvial
  packages/core/demo/data/alluvial.ts
  packages/core/demo/data/index.ts
  packages/core/src/components/graphs/alluvial.ts
  packages/core/src/configuration.ts
  packages/core/src/interfaces/charts.ts
Labels: enhancement
