Repository carbon-design-system/carbon-charts, pull requests merged in 2022-06, with the labels that each got.

#1386 fix(core): add condition to check if domain is not undefined
  packages/core/src/model/heatmap.ts
Labels: bug 🐛

#1391 fix(core): add aria-label attribute to toolbar container
  packages/core/src/components/axes/toolbar.ts
  packages/core/src/services/essentials/dom-utils.ts
Labels: bug 🐛, enhancement, accessibility

#1402 fix(core): remove mock text from axes
  packages/core/src/components/axes/axis.ts
Labels: bug 🐛

#1403 fix(core): remove dom-to-image dependency & add script to project
  packages/core/package.json
  packages/core/src/services/essentials/dom-to-image.js
  packages/core/src/services/essentials/dom-utils.ts
  packages/core/src/tsconfig.json
  yarn-offline-mirror-cache/dom-to-image-2.6.0.tgz
  yarn.lock
Labels: bug 🐛, dependencies
