Repository carbon-design-system/carbon-charts, pull requests merged in 2023-07, with the labels that each got.

#1601 fix: StackBlitz dependencies & render(animate: boolean) values
  packages/angular/package.json
  packages/angular/src/stories/all.stories.ts
  packages/core/package.json
  packages/core/src/chart.ts
  packages/core/src/charts/choropleth.ts
  packages/core/src/charts/heatmap.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/ruler.ts
  packages/core/src/components/essentials/color-scale-legend.ts
  packages/core/src/components/essentials/highlights.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/modal.ts
  packages/core/src/components/essentials/threshold.ts
  packages/core/src/components/essentials/title-meter.ts
  packages/core/src/components/essentials/title.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/components/graphs/tree.ts
  packages/core/src/components/graphs/treemap.ts
  packages/core/src/components/layout/spacer.ts
  packages/core/src/demo/charts/index.ts
  packages/core/src/demo/utils/index.ts
  packages/core/src/demo/utils/package-versions.ts
  packages/core/src/demo/utils/sandbox.ts
  packages/core/src/demo/utils/stackblitz/angular.ts
  packages/core/src/demo/utils/stackblitz/index.ts
  packages/core/src/demo/utils/stackblitz/react.ts
  packages/core/src/demo/utils/stackblitz/svelte.ts
  packages/core/src/demo/utils/stackblitz/vanilla-js.ts
  packages/core/src/demo/utils/stackblitz/vue.ts
  packages/core/src/model/circle-pack.ts
  packages/core/src/tests/test-environment.ts
  packages/core/tsconfig.json
  packages/core/tsconfig.vite.json
  packages/core/vite.config.ts
  packages/react/package.json
  packages/svelte/package.json
  packages/vue/package.json
  tsconfig.json
  yarn.lock
Labels: bug 🐛

#1606 fix(react): remount issues
  package.json
  packages/angular/package.json
  packages/core/package.json
  packages/core/vite.config.ts
  packages/react/package.json
  packages/react/src/charts/BaseChart.tsx
  packages/svelte/package.json
  packages/vue/package.json
  yarn.lock
Labels: bug 🐛

#1610 fix(path)
  package.json
Labels: bug 🐛, build-process

#1617 Stop re-exporting lodash from tools.
  packages/core/src/charts/area.ts
  packages/core/src/charts/combo.ts
  packages/core/src/charts/meter.ts
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/ruler-binned.ts
  packages/core/src/components/axes/ruler.ts
  packages/core/src/components/axes/zoom-bar.ts
  packages/core/src/components/component.ts
  packages/core/src/components/essentials/color-scale-legend.ts
  packages/core/src/components/graphs/alluvial.ts
  packages/core/src/components/graphs/bar-grouped.ts
  packages/core/src/components/graphs/gauge.ts
  packages/core/src/components/graphs/line.ts
  packages/core/src/components/graphs/radar.ts
  packages/core/src/components/graphs/wordcloud.ts
  packages/core/src/configuration.ts
  packages/core/src/model/cartesian-charts.ts
  packages/core/src/model/choropleth.ts
  packages/core/src/model/circle-pack.ts
  packages/core/src/model/heatmap.ts
  packages/core/src/model/model.ts
  packages/core/src/services/color-scale-utils.ts
  packages/core/src/services/essentials/dom-utils.ts
  packages/core/src/services/scales-cartesian.ts
  packages/core/src/tools.ts
Labels: enhancement, build-process, dependencies
