Repository carbon-design-system/carbon-charts, pull requests merged in 2023-12, with the labels that each got.

#1694 fix(model-scalesCartesian):Histogram unable to show negative values on x-axis
  packages/core/src/model/model.ts
  packages/core/src/services/scales-cartesian.ts
Labels: type: bug 🐛

#1702 docs(svelte): add TypeScript reference
  packages/svelte/README.md
Labels: type: docs 📖, package: svelte

#1703 fix(svelte): strongly type dispatched events
  packages/svelte/src/lib/BaseChart.svelte
Labels: type: bug 🐛, package: svelte

#1698 fix(pieModel) : Unable to view model and export CSV while using valueMapsTo
  packages/core/src/model/pie.ts
Labels: type: bug 🐛, severity: 1

#1712 feat(html & CSV): sanitize user input
  packages/core/package.json
  packages/core/src/components/axes/axis.ts
  packages/core/src/components/axes/toolbar.ts
  packages/core/src/components/essentials/legend.ts
  packages/core/src/components/essentials/modal.ts
  packages/core/src/components/essentials/threshold.ts
  packages/core/src/components/essentials/title.ts
  packages/core/src/components/essentials/tooltip.ts
  packages/core/src/model/model.ts
  packages/core/src/utils/sanitizeHtml.ts
  yarn.lock
Labels: type: enhancement 💡
