Repository carbon-design-system/carbon-charts, pull requests merged in 2024-01, with the labels that each got.

#1704 feat(modal):customizability of chart modal
  packages/core/src/model/alluvial.ts
  packages/core/src/model/binned-charts.ts
  packages/core/src/model/boxplot.ts
  packages/core/src/model/bullet.ts
  packages/core/src/model/cartesian-charts.ts
  packages/core/src/model/choropleth.ts
  packages/core/src/model/circle-pack.ts
  packages/core/src/model/gauge.ts
  packages/core/src/model/heatmap.ts
  packages/core/src/model/meter.ts
  packages/core/src/model/model.ts
  packages/core/src/model/pie.ts
  packages/core/src/model/radar.ts
  packages/core/src/model/tree.ts
  packages/core/src/model/treemap.ts
  packages/core/src/model/wordcloud.ts
Labels: type: enhancement 💡, type: a11y ♿

#1725 fix(types): add tabularRepModal interface
  packages/core/src/interfaces/charts.ts
  packages/core/src/interfaces/components.ts
Labels: type: bug 🐛, type: docs 📖

#1726 fix(types): export TabularRepCustomizationOptions
  packages/core/src/index.ts
  packages/core/src/interfaces/index.ts
Labels: type: bug 🐛, type: docs 📖

#1732 chore: onboard @carbon/charts-react to ibm telemetry
  packages/react/README.md
  packages/react/package.json
  packages/react/telemetry.yml
  yarn.lock
Labels: affects: build-process

#1733 chore: onboard other charts flavors to IBM Telemetry
  packages/angular/README.md
  packages/angular/ng-package.json
  packages/angular/package.json
  packages/angular/telemetry.yml
  packages/core/README.md
  packages/core/package.json
  packages/core/telemetry.yml
  packages/core/vite.config.ts
  packages/react/.storybook/main.ts
  packages/svelte/README.md
  packages/svelte/package.json
  packages/svelte/telemetry.yml
  packages/vue/README.md
  packages/vue/package.json
  packages/vue/telemetry.yml
  yarn.lock
Labels: affects: build-process
